// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;

namespace BlazoriseBug.Components
{
    public partial class Colony
    {
        [Key]
        public int ColonyId { get; set; }
        [Required]
        [StringLength(50)]
        public string ColonyName { get; set; }
        [Required]
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        public DateTime DateUpdated { get; set; }
        public bool Archived { get; set; }
    }
}